### ISSUE TITLE
unionviewfuse failure on big file

### ISSUE THREAD

**Issue by neteler** [seiferma/splitviewfuse#7] opened 2016-01-28 13:03 UTC
I tried this promising filesystem on a multi-GB file but unionviewfuse failed:

```
# original data
-rw-r--r-- 1 neteler gis 7198917883 Dec 14 10:36 $HOME/tmp/orig_data/mybigfile.zip

# split
splitviewfuse $HOME/tmp/orig_data $HOME/tmp/split_data -o segmentsize=16777216

# verification
ls -lart $HOME/tmp/split_data/
total 0
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.99
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.98
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.97
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.96
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.95
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.94
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.93
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.92
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.91
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.90
[...]
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.44
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.43
-r--r--r-- 1 neteler gis  1492219 Dec 14 10:36 mybigfile.zip.seg.429
[...]
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.101
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.100
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.10
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.1
-r--r--r-- 1 neteler gis 16777216 Dec 14 10:36 mybigfile.zip.seg.0

# so far ok

# union
unionviewfuse $HOME/tmp/split_data $HOME/tmp/meta_orig_data -o segmentsize=16777216

# verification
ls -lart $HOME/tmp/meta_orig_data
ls: cannot access /home/neteler/tmp/meta_orig_data/mybigfile.zip: No such file or directory
total 0
?????????? ? ?       ?         ?            ? mybigfile.zip

# the used system
uname -a
Linux pgis_north 4.2.7-300.fc23.x86_64 #1 SMP Wed Dec 9 22:28:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

I have no idea how to debug that... suggestions welcome.

**Comment by seiferma** [comment] 2016-02-02 17:35
Hi neteler,

I'm sorry that the filesystem does not work as expected. Unfortunately, you found one of the weak points of the file system: I did not include any logging...

Additing logging would, however, require some time. For now, you could try to specify additional mount options to prevent the file system from running headless: `-o nothreads=True,foreground=True`
If an expection is thrown (which most probably is the reason for this behavior), you should see it in the console window. This could help us to track down the issue.

Nevertheless, I will open an issue for introducing some useful logging.

**Comment by TheDrHax** [comment] 2016-07-10 00:14
This one-line script repairs all files affected by this filesystem:

`find ./ -name "*.seg.*" | sort -V | while read seg; do orig=$(echo $seg | sed 's/\.seg\.[0-9]*//g'); cat "$seg" >> "$orig"; rm "$seg"; done`

Just execute this command in the affected directory and it will concatenate all files ending with .seg.[0-9]\* into the original file and delete the parts. Make sure that you are in the right directory before executing this script. Also I would recommend to make a backup of your files.

Splitviewfuse is very useful but it works only in one direction at the moment. However it is still very helpful to store large updating files in the limited cloud storages.

**Comment by seiferma** [comment] 2016-07-10 09:08
Thanks for your contribution. It sound like you suffer from the same bug as neteler. So, could you provide me a stack trace by executing the filesystem as mentioned above? This, most probably, will allow me to fix unionviewfuse.

**Comment by TheDrHax** [comment] 2016-07-10 14:37
I've tried adding your parameters before writing this script but there were no any output in the terminal. If you can't reproduce this issue on your machine, I would recommend you to use Docker to achieve the similar environment.
1. Install [Docker](https://www.docker.com) (`apt-get install docker.io` on debian or ubuntu)
2. Download [spliteviewfuse_test.tar.gz](https://github.com/seiferma/splitviewfuse/files/356057/spliteviewfuse_test.tar.gz) and unpack it
3. Start terminal in the directory containing these files
4. `chmod +x docker-entrypoint.sh`
5. Build an image (only at the first time): `docker build -t splitviewfuse_test .`
6. Start the container: `docker run -it --rm --privileged splitviewfuse_test`

You will see a shell running inside this container. There are three directories:
- 1 — directory with the original files (contains only one 1 GiB file)
- 2 — splitviewfuse mount of '1' (contains 10 parts 100 MiB each)
- 3 — unionviewfuse mount of '2' (contains one broken file)

`ls -l 3` should output the similar message as in the neteler's example.

**Comment by seiferma** [comment] 2016-07-12 21:47
Thanks @TheDrHax for tracking down the issue and providing me with the required information to reproduce the issue. I found an issue in splitviewfuse related to wrong rounding and another issue in the unionviewfuse file system related to a wrong comparison operator.

I fixed the issues and released a new version via pypi. Could you try the new version and tell me if the issue is fixed for you as well?

**Comment by TheDrHax** [comment] 2016-07-12 22:58
Yes, it works good now. Tested on Ubuntu 16.04, fuse 2.9.4. Thank you!

```
$ md5sum 1/1GB 3/1GB
e37115d4da0e187130ab645dee4f14ed  1/1GB
e37115d4da0e187130ab645dee4f14ed  3/1GB
```

**Comment by seiferma** [comment] 2016-07-13 06:13
Thanks for your fast feedback. I close this issue but feel free to open a new issue if there is another problem.

**Closed as completed by seiferma** 2016-07-13 06:13 UTC
Labels: bug
